### ISSUE TITLE
Template in Jenkins user credentials

### ISSUE THREAD

**Issue by Nightmayr** [Dishout-project/terraform-jenkins#7]
The current CASC yaml file contians pre-defined passwords in plain-text, these need to be replaced with passwords stored as repository secrets in the form `JENKINS_PASSWORD_[USER]` where USER is an approved user of Dishout Jenkins. Taking Henry as an example this secret would be named `JENKINS_PASSWORD_HENRY`. The secret should be set up by the user themselves. The CASC file will be edited to hold a placeholder value matching the title of the secret, e.g 
```  
   users:
      - id: "fortune"
        password: "JENKINS_PASSWORD_FORTUNE"
      - id: "umayr"
        password: "JENKINS_PASSWORD_UMAYR"
      - id: "henry"
        password: "JENKINS_PASSWORD_HENRY"
```
These values will substituted with the secret as part of the Github Action to created the GCP Image. 

The installation process will need to remove this file once it has been used to configure Jenkins, as a user belonging to the sudoers group can inspect this file and see the passwords in plain text. Once the file has been removed the Jenkins Configuration as Code plugin will need to be uninstalled or else it will complain that the casc.yaml is missing.
